# FastAPI backend - reads all 14 InfluxDB instances + serves React dist
. (Join-Path $PSScriptRoot 'load-env.ps1')

# UI host + port
$env:HITRACK_UI_HOST = $env:BACKEND_HOST
$env:HITRACK_UI_PORT = $env:BACKEND_PORT

# Hitachi alert Influx (per site)
$env:HITRACK_INFLUX_CDVL_URL    = "http://127.0.0.1:$env:HITACHI_CDVL_PORT"
$env:HITRACK_INFLUX_CDVL_TOKEN  = $env:HITACHI_CDVL_TOKEN
$env:HITRACK_INFLUX_CDVL_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_CDVL_BUCKET = $env:HITACHI_CDVL_BUCKET

$env:HITRACK_INFLUX_BCP_URL     = "http://127.0.0.1:$env:HITACHI_BCP_PORT"
$env:HITRACK_INFLUX_BCP_TOKEN   = $env:HITACHI_BCP_TOKEN
$env:HITRACK_INFLUX_BCP_ORG     = $env:INFLUX_ORG
$env:HITRACK_INFLUX_BCP_BUCKET  = $env:HITACHI_BCP_BUCKET

$env:HITRACK_INFLUX_SIFY_URL    = "http://127.0.0.1:$env:HITACHI_SIFY_PORT"
$env:HITRACK_INFLUX_SIFY_TOKEN  = $env:HITACHI_SIFY_TOKEN
$env:HITRACK_INFLUX_SIFY_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_SIFY_BUCKET = $env:HITACHI_SIFY_BUCKET

# Brocade alert Influx (per site)
$env:HITRACK_INFLUX_BROCADE_CDVL_URL    = "http://127.0.0.1:$env:BROCADE_CDVL_PORT"
$env:HITRACK_INFLUX_BROCADE_CDVL_TOKEN  = $env:BROCADE_CDVL_TOKEN
$env:HITRACK_INFLUX_BROCADE_CDVL_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_BROCADE_CDVL_BUCKET = $env:BROCADE_CDVL_BUCKET

$env:HITRACK_INFLUX_BROCADE_BCP_URL     = "http://127.0.0.1:$env:BROCADE_BCP_PORT"
$env:HITRACK_INFLUX_BROCADE_BCP_TOKEN   = $env:BROCADE_BCP_TOKEN
$env:HITRACK_INFLUX_BROCADE_BCP_ORG     = $env:INFLUX_ORG
$env:HITRACK_INFLUX_BROCADE_BCP_BUCKET  = $env:BROCADE_BCP_BUCKET

# NetApp alert Influx (per site)
$env:HITRACK_INFLUX_NETAPP_CDVL_URL    = "http://127.0.0.1:$env:NETAPP_CDVL_PORT"
$env:HITRACK_INFLUX_NETAPP_CDVL_TOKEN  = $env:NETAPP_CDVL_TOKEN
$env:HITRACK_INFLUX_NETAPP_CDVL_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_NETAPP_CDVL_BUCKET = $env:NETAPP_CDVL_BUCKET

$env:HITRACK_INFLUX_NETAPP_BCP_URL     = "http://127.0.0.1:$env:NETAPP_BCP_PORT"
$env:HITRACK_INFLUX_NETAPP_BCP_TOKEN   = $env:NETAPP_BCP_TOKEN
$env:HITRACK_INFLUX_NETAPP_BCP_ORG     = $env:INFLUX_ORG
$env:HITRACK_INFLUX_NETAPP_BCP_BUCKET  = $env:NETAPP_BCP_BUCKET

$env:HITRACK_INFLUX_NETAPP_SIFY_URL    = "http://127.0.0.1:$env:NETAPP_SIFY_PORT"
$env:HITRACK_INFLUX_NETAPP_SIFY_TOKEN  = $env:NETAPP_SIFY_TOKEN
$env:HITRACK_INFLUX_NETAPP_SIFY_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_NETAPP_SIFY_BUCKET = $env:NETAPP_SIFY_BUCKET

# Dell alert Influx (per site)
$env:HITRACK_INFLUX_DELL_CDVL_URL    = "http://127.0.0.1:$env:DELL_CDVL_PORT"
$env:HITRACK_INFLUX_DELL_CDVL_TOKEN  = $env:DELL_CDVL_TOKEN
$env:HITRACK_INFLUX_DELL_CDVL_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_DELL_CDVL_BUCKET = $env:DELL_CDVL_BUCKET

$env:HITRACK_INFLUX_DELL_BCP_URL     = "http://127.0.0.1:$env:DELL_BCP_PORT"
$env:HITRACK_INFLUX_DELL_BCP_TOKEN   = $env:DELL_BCP_TOKEN
$env:HITRACK_INFLUX_DELL_BCP_ORG     = $env:INFLUX_ORG
$env:HITRACK_INFLUX_DELL_BCP_BUCKET  = $env:DELL_BCP_BUCKET

$env:HITRACK_INFLUX_DELL_SIFY_URL    = "http://127.0.0.1:$env:DELL_SIFY_PORT"
$env:HITRACK_INFLUX_DELL_SIFY_TOKEN  = $env:DELL_SIFY_TOKEN
$env:HITRACK_INFLUX_DELL_SIFY_ORG    = $env:INFLUX_ORG
$env:HITRACK_INFLUX_DELL_SIFY_BUCKET = $env:DELL_SIFY_BUCKET

# Heartbeat Influx (per site)
$env:HITRACK_HEARTBEAT_CDVL_URL    = "http://127.0.0.1:$env:HEARTBEAT_CDVL_PORT"
$env:HITRACK_HEARTBEAT_CDVL_TOKEN  = $env:HEARTBEAT_CDVL_TOKEN
$env:HITRACK_HEARTBEAT_CDVL_ORG    = $env:INFLUX_ORG
$env:HITRACK_HEARTBEAT_CDVL_BUCKET = $env:HEARTBEAT_CDVL_BUCKET

$env:HITRACK_HEARTBEAT_BCP_URL     = "http://127.0.0.1:$env:HEARTBEAT_BCP_PORT"
$env:HITRACK_HEARTBEAT_BCP_TOKEN   = $env:HEARTBEAT_BCP_TOKEN
$env:HITRACK_HEARTBEAT_BCP_ORG     = $env:INFLUX_ORG
$env:HITRACK_HEARTBEAT_BCP_BUCKET  = $env:HEARTBEAT_BCP_BUCKET

$env:HITRACK_HEARTBEAT_SIFY_URL    = "http://127.0.0.1:$env:HEARTBEAT_SIFY_PORT"
$env:HITRACK_HEARTBEAT_SIFY_TOKEN  = $env:HEARTBEAT_SIFY_TOKEN
$env:HITRACK_HEARTBEAT_SIFY_ORG    = $env:INFLUX_ORG
$env:HITRACK_HEARTBEAT_SIFY_BUCKET = $env:HEARTBEAT_SIFY_BUCKET

# Backend monitor tuning
$env:HITRACK_VERIFY_TLS                 = $env:HITRACK_VERIFY_TLS
$env:HITRACK_PIPELINE_POLL_SECS         = $env:PIPELINE_POLL_SECS
$env:HITRACK_LISTENER_POLL_SECS         = $env:LISTENER_POLL_SECS
$env:HITRACK_LISTENER_DOWN_THRESHOLD_S  = $env:LISTENER_DOWN_THRESHOLD_S

$root = Split-Path -Parent $PSScriptRoot
& "$root\.venv\Scripts\python.exe" "$root\server\server.py"
